version: '2'

services:
  app:
    image: 'client-0.0.1.jar'
    ports:
      - "8080:8080"
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres?currentSchema=builders
      - SPRING_DATASOURCE_USERNAME=client
      - SPRING_DATASOURCE_PASSWORD=client
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=client
      - POSTGRES_PASSWORD=client
