server:
   port: 8080

spring:
   datasource:
      url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=builders}
      username: ${SPRING_DATASOURCE_USERNAME:client}
      password: ${SPRING_DATASOURCE_PASSWORD:client}
   jpa:
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
      hibernate:
         dss-auto: validate